language: rust
rust:
  - stable
  - beta
  - nightly
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - python3-pip
install:
  - pip3 install --user --upgrade mypy flake8
script: ./test-all.sh
cache:
  - cargo
  - pip
