language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - python3-setuptools
install:
  - easy_install3 --user pip
  - python3 -m pip install --user --upgrade mypy flake8
script: ./test-all.sh
cache:
  - cargo
  - pip
