language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
dist: trusty
sudo: false
addons:
    apt:
        packages:
            - python3-pip
install:
    - pip3 install --user --upgrade mypy flake8
    - mypy --version
before_script:
    - cargo uninstall rustfmt || true
    - cargo install --list
    - rustup toolchain install stable
    - rustup component add --toolchain=stable rustfmt-preview
    - rustup component list --toolchain=stable
    - rustup show
    - rustfmt +stable --version || echo fail
    - rustup update
    - rustfmt +stable --version
script: ./test-all.sh
cache:
    cargo: true
    directories:
        - $HOME/.cache/pip
