language: rust
rust:
    - stable
    - beta
dist: trusty
sudo: false
addons:
    apt:
        packages:
            - python3-pip
install:
    - pip3 install --user --upgrade mypy==0.521 flake8
    - travis_wait ./check-rustfmt.sh --install
script: ./test-all.sh
cache:
    cargo: true
    directories:
        - $HOME/.cache/pip
