[package]
name = "cretonne-tools"
authors = ["The Cretonne Project Developers"]
version = "0.5.1"
description = "Binaries for testing the Cretonne libraries"
license = "Apache-2.0"
documentation = "https://cretonne.readthedocs.io/"
repository = "https://github.com/cretonne/cretonne"
publish = false

[[bin]]
name = "cton-util"
path = "src/cton-util.rs"

[dependencies]
cretonne-codegen = { path = "lib/codegen", version = "0.5.1" }
cretonne-reader = { path = "lib/reader", version = "0.5.1" }
cretonne-frontend = { path = "lib/frontend", version = "0.5.1" }
cretonne-wasm = { path = "lib/wasm", version = "0.5.1" }
cretonne-native = { path = "lib/native", version = "0.5.1" }
cretonne-filetests = { path = "lib/filetests", version = "0.5.1" }
cretonne-module = { path = "lib/module", version = "0.5.1" }
cretonne-faerie = { path = "lib/faerie", version = "0.5.1" }
cretonne-simplejit = { path = "lib/simplejit", version = "0.5.1" }
cretonne = { path = "lib/umbrella", version = "0.5.1" }
filecheck = "0.2.1"
docopt = "0.8.0"
serde = "1.0.8"
serde_derive = "1.0.8"
tempdir = "0.3.5"
term = "0.5.1"

[workspace]

# Enable debug assertions and parallel compilation when building cretonne-tools
# since they are for testing and development mostly. This doesn't affect the
# flags used to build the cretonne-* crates when used as a dependency.
[profile.release]
opt-level = 2
debug-assertions = true
codegen-units = 4
