[package]
authors = ["The Cretonne Project Developers"]
name = "cretonne-reader"
version = "0.0.0"
publish = false

[lib]
name = "cton_reader"
path = "lib.rs"

[dependencies]
cretonne = { path = "../libcretonne" }
