[package]
authors = ["The Cretonne Project Developers"]
name = "cretonne-tools"
version = "0.0.0"
description = "Binaries for testing the Cretonne library"
publish = false

[[bin]]
name = "cton-util"
path = "main.rs"

[dependencies]
cretonne = { path = "../../lib/cretonne" }
cretonne-reader = { path = "../../lib/reader" }
filecheck = { path = "../../lib/filecheck" }
docopt = "0.6.80"
rustc-serialize = "0.3.19"
num_cpus = "1.1.0"
