[package]
authors = ["The Cretonne Project Developers"]
name = "cretonne-tools"
version = "0.0.0"
description = "Binaries for testing the Cretonne library"
publish = false

[[bin]]
name = "cton-util"
path = "main.rs"

[dependencies]
cretonne = { path = "../libcretonne" }
cretonne-reader = { path = "../libreader" }
